name: Publish Package

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
jobs:
  check_security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GH repository
        uses: actions/checkout@v6
      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: Install deps
        run: npm ci
      - name: Audit deps
        continue-on-error: false
        run: |
          npm audit
      - name: Check security of module
        continue-on-error: false
        run: |
          npm run security
  integrity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GH repository
        uses: actions/checkout@v6
      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: Install deps
        run: npm ci
      - name: Run integrity check
        continue-on-error: false
        run: |
          npm run test
  check_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GH repository
        uses: actions/checkout@v6
      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: Install deps
        run: npm ci
      - name: Check if package can be published
        continue-on-error: false
        run: |
          npm run test:publish
  publish:
    needs:
      - check_security
      - integrity
      - check_publish
    if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: sqlc
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          # On laisse setup-node vide de toute configuration de registre

      - name: Configure npm for Trusted Publisher and Publish
        run: |
          npm ci
          npm publish --provenance --access public
        env:
          # Ces 3 variables indiquent à npm d'utiliser le jeton OIDC de GitHub à la place d'un token classique
          NPM_CONFIG_REGISTRY: "https://registry.npmjs.org/"
          NPM_CONFIG_AUTH_TYPE: "webauthn"
          npm_config_@mlagie:registry: "https://registry.npmjs.org/"
